name: Auto Push

on:
  schedule:
    - cron: '30 14 * * *'  # Exécuter tous les jours à 14h30
    - cron: '0 10 * * *'   # Exécuter tous les jours à 10h00
    - cron: '0 18 * * *'   # Exécuter tous les jours à 18h00
    - cron: '0 0 * * *'   # Exécuter tous les jours à 18h00
    - cron: '0 21 * * *'   # Exécuter tous les jours à 18h00
  workflow_dispatch:  # Permet de le lancer manuellement si besoin

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configurer Git
      run: |
        git config --global user.name "jayjay1509"
        git config --global user.email "jayson.malet@me.com"

    - name: Mettre à jour le dépôt
      run: |
        git pull origin main --rebase

    - name: Push au dépôt
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/jayjay1509/bot.git
        git add .
        git commit  --allow-empty -m "Automated commit"
        git push origin main